services:
  - type: web
    name: driveu-backend
    runtime: docker
    dockerfilePath: springapp/Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: MAIL_PROVIDER
        value: brevo
      - key: MAIL_API_KEY
        sync: false
      - key: MAIL_FROM_EMAIL
        sync: false
      - key: MAIL_FROM_NAME
        value: DriveU
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_URL
        value: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent
